name: Auto-Update LinkedIn Posts

on:
  schedule:
    - cron: '0 15 * * 5' # Every Friday at 7AM PST (15:00 UTC)
  workflow_dispatch: # Also allows you to manually trigger it from GitHub if needed

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate new posts.json
        run: |
          python generate_posts.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add posts.json
          git commit -m "Auto-update posts.json with new LinkedIn posts [skip ci]" || echo "No changes to commit"
          git push
